<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MieszkanieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MieszkanieRepository extends EntityRepository
{
}
